MEXEC= run.rb
DATADIR= ${HOME}/Code/blogdata
SRCDIR= ${DATADIR}/lynx
OUTDIR= ${DATADIR}/out
REJDIR= ${DATADIR}/reject
EPADIR= ${DATADIR}/epanaphora

run:
	ruby ${MEXEC}

clean:
	#rm ${REJDIR}/*/*
	#rm ${OUTDIR}/*/*
	rm ${EPADIR}/*/*


